# =-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=
# Automatic R script generated via easypar
# 2020-04-24 17:10:26
# =-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=
 
 easypar_generated_function = function(pnad, pnac, pnae)
{
  '... copy your stuff Simulator..
  ...
  ...'
} 
 # EASYPAR Autogenerated R-code
if(sys.nframe() == 0L) {
   args = commandArgs(trailingOnly = TRUE)
   pnad = args[1]
   pnac = args[2]
   pnae = args[3]
print("\nInput parameters for the function\n")
   print(pnad)
   print(pnac)
   print(pnae)
   easypar_generated_function(pnad, pnac, pnae)
}
